<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
        <Authors>Camilo Terevinto</Authors>
        <PackageTags>asp.net core;static website</PackageTags>
        <PackageProjectUrl>https://staticsitegenerator.netlify.app</PackageProjectUrl>
        <RepositoryUrl>https://github.com/CamiloTerevinto/TerevintoSoftware.StaticSiteGenerator</RepositoryUrl>
        <Description>
            A package for creating Static Websites (HTML+CSS+JavaScript) from ASP.NET Core MVC views.
            Read the README in the GitHub project for information on usage.
        </Description>
        <PackageIcon>icon.png</PackageIcon>
        <Version>10.0.0</Version>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <Copyright>Camilo Terevinto</Copyright>
        <IsPackable>true</IsPackable>
        <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
        <PackageOutputPath>Packaged</PackageOutputPath>
        <PackAsTool>true</PackAsTool>
        <OutputType>Exe</OutputType>
        <ToolCommandName>ssg</ToolCommandName>
    </PropertyGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="TerevintoSoftware.StaticSiteGenerator.Tests" />
		<InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
		<None Include="..\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="..\icon.png" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="HtmlAgilityPack" Version="1.12.4" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="[10.0.0,11.0.0)" />
		<PackageReference Include="Spectre.Console" Version="0.54.0" />
        <PackageReference Include="Spectre.Console.Cli" Version="0.53.1" />
    </ItemGroup>

</Project>
